events {}

http {
    server {
        listen 80;

        # Serve frontend HTML
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ =404;
        }

        # Route backend API
        location /api/ {
            proxy_pass http://backend:5000;
        }
        
        location /api/transactions {
            proxy_pass http://transactions:5001;
        }

    }
}
