apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ymb-sprint3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rrc-w2025-cfeasby/DevOps-Assignment-6.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ymb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
